version: '3'
services:

    smartmontools-build:
      image: smartmontools-build
      container_name: smartmontools-build
      environment:
        - SVN_REPOSITORY=https://svn.code.sf.net/p/smartmontools/code/trunk/smartmontools
        - GIT_REPOSITORY=https://github.com/smartmontools/smartmontools
        - GIT_BRANCH=master
      volumes:
        - linux-data:/home/dist

volumes:
    linux-data: